apiVersion: apps/v1
kind: Deployment
metadata:
    name: sdb-ui-deployment
    namespace: sdb
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: sdb-ui-container
                  image: sdb-ui:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 80
