apiVersion: v1
kind: Service
metadata:
    name: sdb-ui-service
    namespace: sdb
spec:
    selector:
        app: frontend
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    type: LoadBalancer
