apiVersion: v1
kind: Service
metadata:
    name: sunshine-daisy-bank-ui-service
    namespace: sunshine-daisy-bank
spec:
    selector:
        app: frontend
    ports:
        - protocol: TCP
          port: 30080
          targetPort: 3000
    type: NodePort
